extends: "eslint:recommended"

env:
    node:       false
    browser:    true
    mocha:      true

parserOptions:
    ecmaVersion: 6
    sourceType: "module"

plugins:
    - "vue"

rules:
    no-unused-vars: 0
    no-console: 0
    no-case-declarations: 0
    semi: 2